autoInstallPeers: false

enablePrePostScripts: true

engineStrict: true

overrides:
  eslint: '9.37.0'

packages:
  - packages/*

publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
  - '*vitest*'

strictPeerDependencies: true
