autoInstallPeers: false

enablePrePostScripts: true

engineStrict: true

minimumReleaseAge: 1140

onlyBuiltDependencies:
  - '@swc/core'
  - 'esbuild'
  - 'unrs-resolver'

packages:
  - packages/*

strictPeerDependencies: true
