autoInstallPeers: false

enablePrePostScripts: true

engineStrict: true

minimumReleaseAge: 1140

onlyBuiltDependencies:
  - '@swc/core'
  - 'esbuild'
  - 'unrs-resolver'

overrides:
  prettier: 3.8.5 # https://github.com/prettier/prettier/issues/19528

packages:
  - packages/*

strictPeerDependencies: true
