autoInstallPeers: false

enablePrePostScripts: true

engineStrict: true

onlyBuiltDependencies:
  - '@swc/core'
  - 'esbuild'
  - 'unrs-resolver'

overrides:
  eslint: '9.37.0'

packages:
  - packages/*

publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
  - '*vitest*'

strictPeerDependencies: true
