name: Copilot Renovate

on:
  pull_request:
    branches:
      - main

jobs:
  copilot-renovate:
    uses: ApiTreeCZ/github-actions/.github/workflows/copilot-renovate.yml@v0.7.0
    secrets:
      OP_APITREE_INFRA_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_APITREE_INFRA_SERVICE_ACCOUNT_TOKEN }}
