name: Copilot

on:
  pull_request:
    branches:
      - main

jobs:
  copilot:
    uses: ApiTreeCZ/github-actions/.github/workflows/copilot.yml@main
    secrets:
      OP_APITREE_INFRA_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_APITREE_INFRA_SERVICE_ACCOUNT_TOKEN }}
