name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      stable:
        description: 'Release stable version'
        required: false
        default: false
        type: boolean

env:
  CACHE_KEY: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
  CACHE_PATH: ./*
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_REMOTE_CACHE_SIGNATURE_KEY: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: release:${{ inputs.stable == true && 'stable' || 'snapshot' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: pnpm run build
      - name: Setup npm registry
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> "$HOME/.npmrc"
      - name: Snapshot release
        if: inputs.stable == false
        run: |
          pnpm changeset version --snapshot next
          pnpm changeset publish --tag next --no-git-tag
      - name: Stable release
        if: inputs.stable == true
        run: |
          pnpm changeset version
          pnpm changeset publish --no-git-tag
          pnpm install
      - name: Commit changes
        if: inputs.stable == true
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "chore: release [skip ci]"
      - name: Create git tags
        if: inputs.stable == true
        run: |
          pnpm changeset tag
      - name: Push changes
        if: inputs.stable == true
        run: |
          git push origin main
          git push origin main --tags
